export type AiOblast = keyof typeof aiOblasts

export const aiOblasts = {
  'Autonomous Republic of Crimea_Автономна Республіка Крим': 'ciua21glebrkckb2',
  'Cherkaska_Черкаська': 'chvmygrlebrkckc3',
  'Chernihivska_Чернігівська': 'clo1x4vlebrkckc4',
  'Chernivetska_Чернівецька': 'ctohs39lebrkckc5',
  'Dnipropetrovska_Дніпропетровська': 'c247whblebrkckc6',
  'Donetska_Донецька': 'cdqzkfalebrkckc7',
  'Ivano-Frankivska_Івано-Франківська': 'ci6107klebrkckc8',
  'Kharkivska_Харківська': 'c4s5fm0lebrkckc9',
  'Khersonska_Херсонська': 'c7f3g3ilebrkckda',
  'Khmelnytska_Хмельницька': 'cuup1d8lebrkckdb',
  'Kirovohradska_Кіровоградська': 'c3uihhnlebrkckdc',
  'Kyiv_Київ': 'c1tv3frlebrkckdd',
  'Kyivska_Київська': 'coi9q1zlebrkckde',
  'Luhanska_Луганська': 'cfje7n6lebrkckdf',
  'Lvivska_Львівська': 'cm6px6xlebrkckdg',
  'Mykolaivska_Миколаївська': 'ctv8cw5lebrkckdh',
  'Odeska_Одеська': 'c23ovtglebrkckdi',
  'Poltavska_Полтавська': 'ciiv648lebrkckdj',
  'Rivnenska_Рівненська': 'chadf69lebrkckdk',
  'Sevastopol_Севастополь': 'c27kgk0lebrkckdl',
  'Sumska_Сумська': 'cj530slebrkckdm',
  'Ternopilska_Тернопільська': 'cx73u5ulebrkckdn',
  'Vinnytska_Вінницька': 'cb1bqpilebrkckdo',
  'Volynska_Волинська': 'cnf4ddvlebrkckdp',
  'Zakarpatska_Закарпатська': 'cesrf15lebrkckdq',
  'Zaporizka_Запорізька': 'cez5t8mlebrkckdr',
  'Zhytomyrska_Житомирська': 'cyx8240lebrkckds',
}
